apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: googletranslate
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: gcr.io/triggermesh/googletranslate:v0.0.6
