apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: trans-twilio
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: gcr.io/triggermesh/transtwilio:v0.0.13
